#!/usr/bin/env python3
"""Check if we need to update the QMK release.
"""

from pathlib import Path

import requests

# Get the pypi version
pypi_qmk = requests.get('https://pypi.org/pypi/qmk/json')

if pypi_qmk.status_code != 200:
    print(f'Could not fetch pypi json: {pypi_qmk.status_code}: {pypi_qmk.text}')
    exit(1)

pypi_qmk_json = pypi_qmk.json()
qmk_pypi_version = pypi_qmk_json['info']['version']

# Get the Debian version
qmk_deb_version = None
os_release = Path('/etc/os-release').read_text()
version_codename='unknown'

for line in os_release.split('\n'):
    if line.startswith('VERSION_CODENAME='):
        version_codename=line.split('=', 1)[1]
        break

qmk_deb_release = requests.get(f'https://debian.qmk.fm/dists/{version_codename}/main/binary-amd64/Packages')

if qmk_deb_release.status_code != 200:
    print(f'Could not fetch %s Packages file: {qmk_deb_release.status_code}: {qmk_deb_release.text}')
    exit(1)

for line in qmk_deb_release.text.split('\n'):
    if line.startswith('Version: '):
        qmk_deb_version = line.split(' ', 1)[1].split('-')[0]
        break

# Check that the versions match
if qmk_pypi_version != qmk_deb_version:
    print(f'{version_codename.title()} packages are out of date!')
    exit(0)
else:
    print(f'{version_codename.title()} packages are up to date!')
    exit(1)
